### ISSUE TITLE
로그인 화면

### ISSUE THREAD

**Issue by msk** [aicers/github-dashboard-client#11]
첫 화면에 구글 계정으로 로그인할 수 있는 화면을 추가합니다. 구체적인 방법은 [Integrating Google Sign-In into your web app](https://developers.google.com/identity/sign-in/web/sign-in)을 참고하세요. 이 이슈에서는 로그인 화면에서 정보를 입력하고 버튼을 누르면 Rust로 작성한 callback 함수가 불리고, 거기에서 [gloo-console](https://docs.rs/gloo-console/latest/gloo_console/index.html)을 이용해 console에 입력받은 이메일 주소를 출력해주는 것으로 합니다. 실제로 구글 API([`GoogleUser.getBasicProfile()`](https://developers.google.com/identity/sign-in/web/reference#googleusergetbasicprofile))를 호출하는 것은 wasm-bindgen을 써야 하므로 다른 이슈에서 다루도록 하겠습니다.

버튼 클릭시 callback 함수를 호출하는 것은 [Build a sample app](https://yew.rs/docs/getting-started/build-a-sample-app)에 예가 나와 있습니다.

클라이언트 ID는 `716252907662-v222gtt44koikgajjokutnqf8ghv2qpb.apps.googleusercontent.com`입니다.

테스트용 JavaScript origin으로는 `http://dashboard.einsis.com:8080`과 `http://localhost:8080`이 등록되어 있습니다.

구현 과정에서 클라이언트 ID 관련 별도 설정이나 권한 등이 필요하면 댓글 달아주세요.

**Comment by msk** [comment]
> 구현중 궁금한점이 있어 댓글을 남깁니다. 로그인 화면의 구현이 [Integrating Google Sign-In into your web app](https://developers.google.com/identity/sign-in/web/sign-in) 을 참조하여 google sign-in 버튼을 구현하고 눌렀을떄 나오는 새창으로 열리는 로그인 화면을 말씀하시는 건가요? 아니면 기본적인 로그인 화면을 구현하고 거기에 구글 계정 sign-in 버튼을 표시하는것으로 구현 하면 되는건가요?

제가 그 부분을 헷갈리게 적었네요. 전자입니다. 구글 계정 이외의 로그인 방법을 제공하지 않으므로 자체 로그인 화면은 필요없습니다.

**Comment by kimhanbeom** [comment]
웹브라우저 화면창에 sign-in 버튼을 띄우기 위해서 아래의 순서로 코드를 진행하였습니다.
 1.  index.html에 필요한 태그(meta name , script)를 작성  
 2.  home.rs의 view에  div 태그를 구현

그러나 trunk serve으로 구동하면 최초에 화면창 접속시에 sign-in 버튼이 보이지만 , 그 후 화면 refresh 하면 버튼이 보이지 않습니다. refresh 후 div에 해당 class 가 적용이 안되는것으로 보이는데 이에 대한 해결 방법을 찾지 못해 어려움을 겪고 있습니다.

**Comment by msk** [comment]
> 웹브라우저 화면창에 sign-in 버튼을 띄우기 위해서 아래의 순서로 코드를 진행하였습니다.
> 
> 1. index.html에 필요한 태그(meta name , script)를 작성
> 2. home.rs의 view에  div 태그를 구현
> 
> 그러나 trunk serve으로 구동하면 최초에 화면창 접속시에 sign-in 버튼이 보이지만 , 그 후 화면 refresh 하면 버튼이 보이지 않습니다. refresh 후 div에 해당 class 가 적용이 안되는것으로 보이는데 이에 대한 해결 방법을 찾지 못해 어려움을 겪고 있습니다.

@sehkone #12 코드 좀 봐 주세요.

**Comment by kimhanbeom** [comment]
> > 웹브라우저 화면창에 sign-in 버튼을 띄우기 위해서 아래의 순서로 코드를 진행하였습니다.
> > 
> > 1. index.html에 필요한 태그(meta name , script)를 작성
> > 2. home.rs의 view에  div 태그를 구현
> > 
> > 그러나 trunk serve으로 구동하면 최초에 화면창 접속시에 sign-in 버튼이 보이지만 , 그 후 화면 refresh 하면 버튼이 보이지 않습니다. refresh 후 div에 해당 class 가 적용이 안되는것으로 보이는데 이에 대한 해결 방법을 찾지 못해 어려움을 겪고 있습니다.
> 
> @kimhanbeom 버튼이 보이는 화면과 refresh 후 보이지 않는 화면을 스크린샷으로 여기에 좀 올려봐 주세요

@sehkone 다음과 같이 처음 실행 했을 때 버튼이 보이고 refresh 후에는 보이지 않습니다.
![01](https://user-images.githubusercontent.com/104803357/180335095-64a6af62-92b4-4491-993b-846fb8f09c62.png)

![02](https://user-images.githubusercontent.com/104803357/180335163-77d7e42a-7e0c-48b3-8485-59efa6a78d6c.png)

**Comment by sehkone** [comment]
이 내용 한번 참고하세요.

https://stackoverflow.com/questions/70993933/why-does-the-sign-in-with-google-button-disappear-after-i-render-it-the-second-t

**Comment by msk** [comment]
기본적인 기능에 문제가 없으면 그것만으로 PR을 올리고, 버튼이 사라지는 문제는 별도 이슈로 올려서 추후 해결하는 것도 괜찮습니다.

**Comment by kimhanbeom** [comment]
버튼에 관련해서 제가 드린 설명이 부족했습니다. 정확한 상태는 다음과 같습니다.
 1. trunk serve 후 최초 접속시 버튼이 무조건 표시됩니다.
 2. refresh 후 버튼 미표시 됩니다.
 3. trunk 종료 후 trunk  serve 다시 하면 refresh 떄 처럼 버튼이 미표시됩니다.
 4. 간혹 [3]을 반복하다보면 아주 드물지만 버튼이 표시되는 경우도 있습니다.
 
현재 웹브라우저의 인터넷 기록을 삭제하고 주소로 접속하면 버튼이 항상 표시되는것이 확인되었으니 현재 이슈의 기본적인 기능 관련해서 먼저 진행하겠습니다.

**Comment by kimhanbeom** [comment]
@msk
구현중 궁금한 점이 있어 댓글을 남깁니다.
구현된 구글 로그인 버튼을 누르고 sign in을 진행할 경우 결국에는 새 창에서 메일/pw를 입력하는데 , 새 창에서의 입력 이벤트를 버튼구현화면의 callback/update에서 처리하는 방법이 보이지 않습니다.

**Comment by msk** [comment]
> @msk 구현중 궁금한 점이 있어 댓글을 남깁니다. 구현된 구글 로그인 버튼을 누르고 sign in을 진행할 경우 결국에는 새 창에서 메일/pw를 입력하는데 , 새 창에서의 입력 이벤트를 버튼구현화면의 callback/update에서 처리하는 방법이 보이지 않습니다.

새 창에서 인증 완료하고 난 다음 `onSignIn`이 불리지 않나요? "새 창에서의 입력 이벤트"는 어떤 이벤트를 말씀하시는 건가요?

**Comment by kimhanbeom** [comment]
1. 새창 입력 이벤트는 말씀주신 새창에서의 인증 부분을 의미합니다.
2. 새창에서 인증 완료 후 js의 onSignIn 이 호출되어 console 정보가 표시되고 있습니다.
3. onSignIn은 google Sign-in의 성공에 대한 js의 처리부인데 , 이것을 현재 화면의 callback함수와 연동시키는 방법이 보이지 않습니다.

**Comment by msk** [comment]
Resolved by #12.
