### ISSUE TITLE
서버로 GraphQL 쿼리를 보내고 결과 출력

### ISSUE THREAD

**Issue by msk** [aicers/github-dashboard-client#4]
현재 클라이언트 화면에는 `home::view`에서 출력하는 "AICE GitHub Dashboard"란 문자열만 나오고 있습니다. 앞으로는 서버에서 가져온 이슈들을 보여줄 예정입니다.

이 이슈에서는 그 첫 단계로, `home::view` 내에서 [gloo-net](https://docs.rs/gloo-net/latest/gloo_net/)을 써서 서버로 다음과 같은 문자열을 보내고(이후에는 쿼리에 변수가 포함되므로 async-graphql을 써서 보내겠지만, 지금은 변수가 없으므로 단순 문자열로 보내면 됩니다),

```json
{
  "query": "{ issues }"
}
```

그 결과를 그대로 문자열로 출력하도록 합니다.

현재 버전의 서버를 구동한 상태에서 클라이언트를 실행(trunk serve)하고 브라우저 주소창에 `http://127.0.0.1:8080/`을 입력하면 아래 문자열이 브라우저에 출력되어야 합니다.

```
{"data":{"issues":[]}}
```

쿼리를 보낼 때에는 쿼리를 보내고 그에 대한 응답을 처리하는 `async` 함수를 만들어서 [`send_future`](https://docs.rs/yew/latest/yew/html/struct.Scope.html#method.send_future)에 인자로 넘겨주면 됩니다. 인자로 주는 `async` 함수는 리턴값이 [`Component::update`](https://docs.rs/yew/latest/yew/html/trait.Component.html#method.update)에서 처리하는 [`Message`](https://docs.rs/yew/latest/yew/html/trait.Component.html#associatedtype.Message)타입이어야 합니다.

**Comment by BLYKIM** [comment]
구현하는거랑 별개의 질문으로
All the code from reqwasm was was moved to gloo as part of https://github.com/rustwasm/gloo/pull/191. Move to gloo-net should be a drop-in replacement for reqwasm users
라고 써있는데 gloo-net이 아닌 reqwasm을 쓰는 이유가 따로 있는지 궁금합니다

**Comment by msk** [comment]
> 구현하는거랑 별개의 질문으로 All the code from reqwasm was was moved to gloo as part of [rustwasm/gloo#191](https://github.com/rustwasm/gloo/pull/191). Move to gloo-net should be a drop-in replacement for reqwasm users 라고 써있는데 gloo-net이 아닌 reqwasm을 쓰는 이유가 따로 있는지 궁금합니다

gloo-net을 쓰는 것이 맞습니다. 제가 잘못 적었네요. 지적 감사합니다. 이슈 설명도 고쳐놓도록 하겠습니다.
